# Generated by Django 2.0.6 on 2019-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Recent',
            },
        ),
    ]
